
- name: reload systemd configuration
  systemd:
    daemon_reload: true

# Restart service and ensure it is enabled

- name: restart elasticsearch
  service: name={{instance_init_script | basename}} state=restarted enabled=yes
  when:
    - es_restart_on_change
    - es_start_service
  register: es_restarted
